const data = [
  "Quis et sit id non anim mollit proident. Irure incididunt dolore deserunt id magna elit. Eiusmod sint esse labore eiusmod minim magna ut. Excepteur proident deserunt est officia mollit sit nisi magna labore sint mollit irure amet tempor. Esse excepteur mollit nulla nulla consequat labore.",
  "In sit incididunt ipsum et. Veniam laborum voluptate laborum laboris fugiat et ut irure aute eiusmod. Et ullamco ullamco est quis sit pariatur ipsum in officia tempor. Irure officia nulla aute est nostrud quis anim mollit sint do id aliquip.",
  "Dolor cupidatat irure ex ullamco ea et consequat proident in. Nulla quis consectetur occaecat qui mollit elit culpa ad reprehenderit laborum occaecat fugiat. Irure exercitation consectetur enim aliqua non cupidatat irure eiusmod nostrud veniam incididunt deserunt. Deserunt dolore laboris ex id eiusmod aliquip exercitation magna dolore eu ad.",
  "Labore dolor cillum nostrud in. Cillum est magna eu ipsum. Sit duis pariatur exercitation ea eu. Fugiat quis ullamco irure pariatur consequat.",
  "Officia id fugiat adipisicing esse nostrud. Ad amet pariatur mollit pariatur esse reprehenderit. Consectetur aute sunt excepteur dolore sunt quis exercitation mollit. Voluptate Lorem nisi sint nisi laborum magna mollit enim sint laborum id fugiat velit quis. Aliquip proident labore sunt aute. Reprehenderit id est commodo anim in dolor aliqua occaecat cupidatat anim eiusmod. Eu ipsum anim cillum enim dolore minim fugiat nisi sit sunt.",
  "Laborum excepteur velit cupidatat sunt tempor sint. Non proident dolor amet quis duis ullamco et ad non minim sit ullamco. Non irure dolore sunt reprehenderit id duis anim deserunt nulla minim anim quis commodo dolore. Commodo irure Lorem ea sunt dolore sint enim laborum ex eiusmod quis nostrud commodo enim.",
  "Lorem dolore ut nostrud aliquip occaecat tempor irure ex ad. Cupidatat sint elit adipisicing sunt nisi et. Eu reprehenderit sit minim nulla quis elit commodo est Lorem enim voluptate. Aute nostrud elit deserunt nostrud ea dolore Lorem pariatur consequat consectetur. In velit eiusmod esse aliqua ad voluptate sit labore. Tempor sit do voluptate non. Occaecat mollit qui pariatur voluptate enim et amet dolor elit laborum deserunt Lorem excepteur dolor.",
  "Reprehenderit qui esse adipisicing voluptate adipisicing quis nulla. Cupidatat aute enim irure velit aliquip non cupidatat. Laboris tempor proident laborum sunt culpa nulla non minim ullamco. Tempor qui deserunt ut adipisicing ullamco et ex mollit elit aliquip proident cillum. Eiusmod fugiat laboris incididunt ullamco incididunt sunt elit veniam ex nulla sint dolore dolore. Minim excepteur duis nisi aliqua consectetur mollit officia.",
  "Sint ullamco esse aliqua incididunt. Esse laborum dolore sit et velit consectetur ipsum cillum. Eu est anim esse elit. Sint minim amet exercitation irure ipsum ipsum. Proident quis est adipisicing consequat laboris minim consectetur sint velit nulla. Proident officia ex velit id consequat in sit commodo anim minim aliquip ut.",
];

export default data;
